[tool.poetry]
name = "mubi-live"
version = "0.1.0"
description = ""
authors = ["Mathieu Dhondt <laundro@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
